Question1Screen

<Question1Screen>:
    BoxLayout:
        orientation: "vertical"
        BoxLayout:
            orientation: "vertical"
            Label:
                text:"What color is a carrot"
        BoxLayout:
            Button:
                text: "I Think its uhhhhh"
            Button:
                text: "yeah its uhhhhh"
            Button:
                text: "carrot uhhh"

